### ISSUE TITLE
Timer Exceptions

### ISSUE THREAD

**Issue by mplewis7** [460Game/King-Slayer#80]
Exception in thread "Timer-0" java.lang.IndexOutOfBoundsException: Index: 0, Siz
e: 0
        at java.util.LinkedList.checkElementIndex(Unknown Source)
        at java.util.LinkedList.get(Unknown Source)
        at game.model.game.model.worldObject.entity.aiStrat.MinionStrat$Resource
MinionStrat.wander(MinionStrat.java:348)
        at game.model.game.model.worldObject.entity.aiStrat.MinionStrat$Resource
MinionStrat.handleEnemyDetected(MinionStrat.java:269)
        at game.model.game.model.worldObject.entity.aiStrat.MinionStrat.updateAI
(MinionStrat.java:695)
        at game.model.game.model.worldObject.entity.Entity.lambda$updateAI$0(Ent
ity.java:220)
        at java.util.Optional.ifPresent(Unknown Source)
        at game.model.game.model.worldObject.entity.Entity.updateAI(Entity.java:
220)
        at game.model.game.model.GameModel.lambda$updateAI$12(GameModel.java:235
)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at game.model.game.model.GameModel.updateAI(GameModel.java:235)
        at game.model.game.model.ServerGameModel$2.run(ServerGameModel.java:233)

        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)

**Comment by mplewis7** [comment]
Exception in thread "Timer-44" java.util.NoSuchElementException: No value presen
t
        at java.util.Optional.get(Unknown Source)
        at game.ai.Astar.getClosestMetal(Astar.java:346)
        at game.model.game.model.worldObject.entity.aiStrat.MinionStrat$Resource
MinionStrat.wander(MinionStrat.java:316)
        at game.model.game.model.worldObject.entity.aiStrat.MinionStrat.updateAI
(MinionStrat.java:702)
        at game.model.game.model.worldObject.entity.Entity.lambda$updateAI$0(Ent
ity.java:220)
        at java.util.Optional.ifPresent(Unknown Source)
        at game.model.game.model.worldObject.entity.Entity.updateAI(Entity.java:
220)
        at game.model.game.model.GameModel.lambda$updateAI$12(GameModel.java:235
)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at game.model.game.model.GameModel.updateAI(GameModel.java:235)
        at game.model.game.model.ServerGameModel$2.run(ServerGameModel.java:233)

        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)
